### ISSUE TITLE
Could you please upload some test results?

### ISSUE THREAD

**Issue by Fivethousand5k** [zhangzhao2022/pointscatter#1]
Hi! Thank you for your excellent work! May I ask if you could upload the test results so we do not have to train networks from scratch?

**Comment by zhangzhao2022** [comment]
> 

Pretrained models can be found in Readme.md

**Comment by zhangzhao2022** [comment]
> Hi! Thank you for your excellent work! May I ask if you could upload the test results so we do not have to train networks from scratch?

Pretrained models can be found in Readme.md

**Comment by zhangzhao2022** [comment]
> Hi! Thank you for your excellent work! May I ask if you could upload the test results so we do not have to train networks from scratch?

Pretrained models of the 4 datasets based on unet can be found in Readme.md
