### ISSUE TITLE
How do you extract graphs from binary segmentation results?

### ISSUE THREAD

**Issue by Fivethousand5k** [zhangzhao2022/pointscatter#4]
Hi, sorry for bothering you again. 

I notice that there is a topological metric $X_{error}$ in your evaluation, which computes the mean absolute error of the Euler characteristic.  However, without knowing how you extract a graph from the binary segmentation, I could not perform a fair comparison with yours. 

Could you please give more details on generating graphs from binary segmentation results or post a repo that I could refer to？ Btw, I have checked the repo of Cldice, which you followed,  but found nothing useful.

Many thanks!

**Comment by zhangzhao2022** [comment]
You may need to refer to the supp. material of <Cldice>

Zhao Zhang


 ***@***.***
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  03/30/2023 12:45 To  ***@***.***> Cc  ***@***.***> Subject  [zhangzhao2022/pointscatter] How do you extract graphs from binary segmentation results? (Issue #4)  

Hi, sorry for bothering you again.
I notice that there is a topological metric $X_{error}$ in your evaluation, which computes the mean absolute error of the Euler characteristic. However, without knowing how you extract a graph from the binary segmentation, I could not perform a fair comparison with yours.
Could you please give more details on generating graphs from binary segmentation results or post a repo that I could refer to？ Btw, I have checked the repo of Cldice, which you followed, but found nothing useful.
Many thanks!

**Comment by Fivethousand5k** [comment]
Thanks, I figured it out.
